### ISSUE TITLE
License

### ISSUE THREAD

**Issue by devkral** [h2g2bob/ipp-server#1]
Sry for bothering you. What is the license of this project?

Do you want help?

**Comment by h2g2bob** [comment]
Oops, I should have added a license of some sort.

I'll put a GPLv3 license on it later today - it's the default I add if I
haven't thought about what I should license it as. If you need a more
permissive license than that, shout and I'll think about it some more.

I'm not really doing anything with the code at the moment, but I'm always
happy to recieve patches.

I should point out that I made this to learn about how IPP works. It's
certain to fall over if put under any significant load and might only work
with certain versions of cups. If you're looking for a fun project which is
easy(ish) to understand, this is the project for you! If you're looking for
a robust solution to a real-world problem, then I'm pretty sure the CUPS
people would have better ideas, although it might be obscured by their
dense, unreadable documentation.

**Comment by devkral** [comment]
thank you. It is for a university project

**Comment by devkral** [comment]
I would recommend LGPL2.1 or BSD/MIT.  GPL3 can backfire: You cannot push your programs in app stores without violating your own license (right to reverse engineer).
GPL2 has some problems with reinstating rights if you have violated them once and is also not very app store friendly (see vlc relicense).

Disclaimer: I am not a lawyer.

**Comment by devkral** [comment]
I am using MIT/BSD license to not have to think about it and being able to relicense.

**Comment by h2g2bob** [comment]
Hmm, the app store issue appears to only be a problem for the Apple store, while the Google Play store is compatible with the GPL. This presumably means "app store being a jerk" leads to "increased development costs for apps targeting that store", which I'm totally happy about.

It looks like creative commons licenses have the same problem (no "technological measures").

But what about this code? The risk of permissive licenses is someone taking the code and not sharing improvements (eg: selling an improved version -- unlikely with this code!). I'd be happy with that for this code: it's just a toy / learning project. I'll make it 2-clause BSD.
