### ISSUE TITLE
spaces instead tabs

### ISSUE THREAD

**Issue by devkral** [h2g2bob/ipp-server#3]
Tabs are seldom used in python programming as they tend to break code (mixed tabs and spaces) and have a variable width.
Would it be ok if I transform your tabs into spaces?

**Comment by h2g2bob** [comment]
Sure, go ahead! Spaces are more correct.

(Using tabs is a bad habit I have - it's what I use at work, as nobody's had the guts to run `sed` over the whole codebase yet...)

**Comment by devkral** [comment]
I can recommend you atom (editor). It has a nice feature that converts tabs into spaces, softtab (every tab you type is transformed into 4 spaces), next to much other cool stuff
